# Generated by Django 6.1.1 on 2026-09-25 21:39

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('paired', 'paired'), ('series', 'series'), ('replay', 'replay'), ('warmup', 'warmup'), ('observational', 'observational')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('proposition', models.TextField(blank=True, default='')),
                ('leans', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('active', 'active'), ('closed', 'closed')], default='open', max_length=10)),
                ('source', models.CharField(choices=[('human', 'human'), ('synthetic', 'synthetic')], default='human', max_length=10)),
                ('pair_id', models.CharField(blank=True, default='', max_length=100)),
                ('variant', models.CharField(blank=True, default='', max_length=100)),
                ('transcript_id', models.CharField(blank=True, default='', max_length=100)),
                ('label_seed', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='forum.experiment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='forum.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('\\A[A-Z]\\Z', 'The label must be one uppercase letter, A to Z.')])),
                ('join_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='forum.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('author_type', models.CharField(choices=[('user', 'user'), ('moderator', 'moderator')], max_length=10)),
                ('content', models.TextField()),
                ('char_count', models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('planted', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='forum.conversation')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='forum.message')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='forum.participant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('conversation', 'label'), name='forum_participant_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('conversation', 'join_order'), name='forum_participant_join_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('conversation', 'user'), name='forum_participant_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('label__gte', 'A'), ('label__lte', 'Z'), django.db.models.lookups.Exact(django.db.models.functions.text.Length('label'), 1)), name='forum_participant_label_a_to_z'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('join_order__gte', 1)), name='forum_participant_join_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq_no'), name='forum_message_seq_unique'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('seq_no__gte', 1)), name='forum_message_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('char_count__gte', 1)), name='forum_message_char_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_type', 'moderator'), _negated=True), ('participant__isnull', True), _connector='OR'), name='forum_message_moderator_has_no_participant'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_type', 'user'), _negated=True), ('participant__isnull', False), _connector='OR'), name='forum_message_user_has_participant'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('transcript_id', ''), _negated=True), fields=('experiment', 'transcript_id'), name='forum_conversation_transcript_unique_per_experiment'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'active', 'closed'])), name='forum_conversation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['human', 'synthetic'])), name='forum_conversation_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['paired', 'series', 'replay', 'warmup', 'observational'])), name='forum_experiment_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('author_type__in', ['user', 'moderator'])), name='forum_message_author_type_valid'),
        ),
    ]
