# Generated by Django 6.1.1 on 2026-09-26 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_proposition_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='side',
            field=models.CharField(blank=True, choices=[('pro', 'pro'), ('con', 'con')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='topic',
            name='opposing_position',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('side', ''), _negated=True), fields=('conversation', 'side'), name='forum_participant_side_unique_per_conversation'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['', 'pro', 'con'])), name='forum_participant_side_valid'),
        ),
    ]
