# Generated by Django 6.1.1 on 2026-09-25 19:35

import moderation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaker_tripped', models.BooleanField(default=False)),
                ('tripped_at', models.DateTimeField(blank=True, null=True)),
                ('trip_reason', models.CharField(blank=True, choices=[('spend_limit', 'spend_limit'), ('consecutive_errors', 'consecutive_errors'), ('manual', 'manual')], default='', max_length=30)),
                ('trip_detail', models.TextField(blank=True, default='')),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='guardstate_single_row')],
            },
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('moderation', 'moderation'), ('spike', 'spike'), ('golden', 'golden'), ('replay', 'replay'), ('judge', 'judge')], max_length=20)),
                ('run_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('conversation_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('agent', models.CharField(blank=True, default='', max_length=50)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('provider', models.CharField(default='anthropic', max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_tokens', models.PositiveIntegerField()),
                ('request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('parsed', models.JSONField(blank=True, null=True)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=50)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('error', 'error'), ('refused_budget', 'refused_budget'), ('refused_breaker', 'refused_breaker'), ('refused_disabled', 'refused_disabled'), ('refused_model', 'refused_model')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=moderation.models._now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['purpose', 'status', 'created_at'], name='moderation__purpose_f86aa2_idx')],
            },
        ),
    ]
