# Generated by Django 6.1.1 on 2026-09-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardstate',
            name='cooldown_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guardstate',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardstate',
            name='last_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardstate',
            name='last_alert_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guardstate',
            name='probe_in_flight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardstate',
            name='probe_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardstate',
            name='trip_kind',
            field=models.CharField(blank=True, choices=[('hard', 'hard'), ('soft', 'soft')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='guardstate',
            name='trip_reason',
            field=models.CharField(blank=True, choices=[('spend_limit', 'spend_limit'), ('consecutive_errors', 'consecutive_errors'), ('auth_error', 'auth_error'), ('manual', 'manual')], default='', max_length=30),
        ),
    ]
