# Generated by Django 6.1.1 on 2026-09-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_guardstate_cooldown_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardstate',
            name='trip_reason',
            field=models.CharField(blank=True, choices=[('spend_limit', 'spend_limit'), ('consecutive_errors', 'consecutive_errors'), ('auth_error', 'auth_error'), ('billing_error', 'billing_error'), ('manual', 'manual')], default='', max_length=30),
        ),
    ]
