# Generated by Django 6.1.1 on 2026-09-25 21:39

import django.db.models.deletion
import moderation.models
from django.db import migrations, models

# Database triggers (plan section 2, layer 2). SQLite only, like the rest of the project. A violated trigger raises
# django.db.utils.IntegrityError, so raw SQL, bulk_create, queryset update() and the admin cannot get around save().
# Each entry is (trigger name, CREATE statement); the reverse drops the trigger by name.
_RUN = "moderation_moderationrun"
_TRIGGERS = [
    (
        "moderation_run_trigger_must_be_user_insert",
        f"""CREATE TRIGGER moderation_run_trigger_must_be_user_insert
BEFORE INSERT ON {_RUN}
FOR EACH ROW
WHEN (SELECT author_type FROM forum_message WHERE id = NEW.trigger_message_id) IS NOT 'user'
BEGIN
    SELECT RAISE(ABORT, 'moderation run trigger_message must be a user message');
END""",
    ),
    (
        "moderation_run_trigger_must_be_user_update",
        f"""CREATE TRIGGER moderation_run_trigger_must_be_user_update
BEFORE UPDATE OF trigger_message_id ON {_RUN}
FOR EACH ROW
WHEN (SELECT author_type FROM forum_message WHERE id = NEW.trigger_message_id) IS NOT 'user'
BEGIN
    SELECT RAISE(ABORT, 'moderation run trigger_message must be a user message');
END""",
    ),
    (
        "moderation_run_posted_must_be_moderator_insert",
        f"""CREATE TRIGGER moderation_run_posted_must_be_moderator_insert
BEFORE INSERT ON {_RUN}
FOR EACH ROW
WHEN NEW.posted_message_id IS NOT NULL
    AND (SELECT author_type FROM forum_message WHERE id = NEW.posted_message_id) IS NOT 'moderator'
BEGIN
    SELECT RAISE(ABORT, 'moderation run posted_message must be a moderator message');
END""",
    ),
    (
        "moderation_run_posted_must_be_moderator_update",
        f"""CREATE TRIGGER moderation_run_posted_must_be_moderator_update
BEFORE UPDATE OF posted_message_id ON {_RUN}
FOR EACH ROW
WHEN NEW.posted_message_id IS NOT NULL
    AND (SELECT author_type FROM forum_message WHERE id = NEW.posted_message_id) IS NOT 'moderator'
BEGIN
    SELECT RAISE(ABORT, 'moderation run posted_message must be a moderator message');
END""",
    ),
    # The two triggers below are on forum_message, not on the run table. They close a bypass: without them,
    # Message.objects.filter(...).update(author_type=...) could turn a run's trigger message into a moderator message,
    # or its posted message into a user message, after the run was validated. They fire only for messages that a
    # run references, so ordinary message updates are unaffected.
    (
        "moderation_run_trigger_message_stays_user",
        f"""CREATE TRIGGER moderation_run_trigger_message_stays_user
BEFORE UPDATE OF author_type ON forum_message
FOR EACH ROW
WHEN NEW.author_type IS NOT 'user'
    AND EXISTS (SELECT 1 FROM {_RUN} WHERE trigger_message_id = OLD.id)
BEGIN
    SELECT RAISE(ABORT, 'a message that triggered a moderation run must stay a user message');
END""",
    ),
    (
        "moderation_run_posted_message_stays_moderator",
        f"""CREATE TRIGGER moderation_run_posted_message_stays_moderator
BEFORE UPDATE OF author_type ON forum_message
FOR EACH ROW
WHEN NEW.author_type IS NOT 'moderator'
    AND EXISTS (SELECT 1 FROM {_RUN} WHERE posted_message_id = OLD.id)
BEGIN
    SELECT RAISE(ABORT, 'a message posted by a moderation run must stay a moderator message');
END""",
    ),
]


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('moderation', '0003_alter_guardstate_trip_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(max_length=50)),
                ('issue_type', models.CharField(choices=[('unsupported_claim', 'unsupported_claim'), ('possible_factual_error', 'possible_factual_error'), ('unclear_statement', 'unclear_statement'), ('fallacy', 'fallacy'), ('strawman', 'strawman'), ('abusive_language', 'abusive_language'), ('repetition', 'repetition'), ('process_violation', 'process_violation')], max_length=40)),
                ('dimension', models.CharField(blank=True, choices=[('', ''), ('factual_accuracy', 'factual_accuracy'), ('abusiveness', 'abusiveness')], default='', max_length=30)),
                ('quote', models.TextField(blank=True, default='')),
                ('quote_start', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_end', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_match', models.CharField(choices=[('exact', 'exact'), ('normalized', 'normalized'), ('not_found', 'not_found')], default='not_found', max_length=12)),
                ('explanation', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('intensity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('validity', models.CharField(choices=[('valid', 'valid'), ('rejected', 'rejected')], default='valid', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='forum.message')),
            ],
        ),
        migrations.CreateModel(
            name='IssueDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(choices=[('acted', 'acted'), ('declined', 'declined')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposition', to='moderation.issue')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('live', 'live'), ('replay', 'replay')], default='live', max_length=10)),
                ('replicate', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('failed', 'failed'), ('skipped_budget', 'skipped_budget'), ('skipped_disabled', 'skipped_disabled')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('is_stale', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, choices=[('', ''), ('intervene', 'intervene'), ('no_intervention', 'no_intervention')], default='', max_length=20)),
                ('rationale', models.TextField(blank=True, default='')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=50)),
                ('error', models.TextField(blank=True, default='')),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('discussion_map', models.JSONField(blank=True, default=dict)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=moderation.models._now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_runs', to='forum.conversation')),
                ('posted_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_by_run', to='forum.message')),
                ('replay_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replays', to='moderation.moderationrun')),
                ('trigger_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_runs', to='forum.message')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='moderation.moderationrun'),
        ),
        migrations.CreateModel(
            name='InterventionAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('act_type', models.CharField(choices=[('provide_information', 'provide_information'), ('correct_factual_error', 'correct_factual_error'), ('improve_argumentation', 'improve_argumentation'), ('clarify_argument', 'clarify_argument'), ('restate_positions', 'restate_positions'), ('identify_agreement_disagreement', 'identify_agreement_disagreement'), ('request_information', 'request_information'), ('request_clarification', 'request_clarification'), ('enforce_conduct', 'enforce_conduct'), ('enforce_process', 'enforce_process')], max_length=40)),
                ('tone', models.CharField(choices=[('gentle', 'gentle'), ('neutral', 'neutral'), ('firm', 'firm')], max_length=10)),
                ('text', models.TextField()),
                ('addressee', models.CharField(max_length=3)),
                ('subject', models.CharField(max_length=4)),
                ('validity', models.CharField(choices=[('valid', 'valid'), ('rejected', 'rejected')], default='valid', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('char_len', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_question', models.BooleanField(default=False)),
                ('quotes_participant', models.BooleanField(default=False)),
                ('source_messages', models.ManyToManyField(blank=True, related_name='acts_sourced', to='forum.message')),
                ('source_issues', models.ManyToManyField(blank=True, related_name='acts', to='moderation.issue')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='moderation.moderationrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='moderationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'live')), fields=('trigger_message',), name='moderationrun_one_live_per_trigger'),
        ),
        migrations.AddConstraint(
            model_name='moderationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'replay'), _negated=True), ('posted_message__isnull', True), _connector='OR'), name='moderationrun_replay_never_posts'),
        ),
        migrations.AddConstraint(
            model_name='moderationrun',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='moderationrun_attempts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='moderationrun',
            constraint=models.CheckConstraint(condition=models.Q(('replicate__gte', 1)), name='moderationrun_replicate_positive'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('run', 'local_id'), name='issue_unique_local_id_per_run'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('intensity__isnull', True), models.Q(('intensity__gte', 0), ('intensity__lte', 4)), _connector='OR'), name='issue_intensity_in_range'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quote_end__isnull', True), ('quote_match', 'not_found'), ('quote_start__isnull', True)), models.Q(models.Q(('quote_match', 'not_found'), _negated=True), ('quote_end__isnull', False), ('quote_start__isnull', False)), _connector='OR'), name='issue_not_found_iff_no_offsets'),
        ),
        migrations.AddConstraint(
            model_name='interventionact',
            constraint=models.UniqueConstraint(fields=('run', 'order'), name='interventionact_unique_order_per_run'),
        ),
        migrations.AddConstraint(
            model_name='interventionact',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='interventionact_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='interventionact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('validity', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='interventionact_rejected_needs_reason'),
        ),

        *[
            migrations.RunSQL(sql=create, reverse_sql=f"DROP TRIGGER IF EXISTS {name}")
            for name, create in _TRIGGERS
        ],
    ]
