# Generated by Django 6.1.1 on 2026-09-26 22:04

import django.db.models.deletion
import moderation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('moderation', '0004_moderation_run_issue_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_text', models.TextField()),
                ('char_count', models.PositiveIntegerField()),
                ('draft_sha256', models.CharField(max_length=64)),
                ('snapshot_seq', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=3)),
                ('outcome', models.CharField(choices=[('no_concern', 'no_concern'), ('concern', 'concern'), ('unavailable', 'unavailable')], max_length=12)),
                ('unavailable_reason', models.CharField(blank=True, choices=[('', ''), ('off', 'off'), ('rate_limited', 'rate_limited'), ('llm_disabled', 'llm_disabled'), ('budget', 'budget'), ('breaker', 'breaker'), ('refused', 'refused'), ('structural', 'structural'), ('api_error', 'api_error'), ('internal_error', 'internal_error')], default='', max_length=20)),
                ('note_texts', models.JSONField(blank=True, default=list)),
                ('master_output', models.JSONField(blank=True, null=True)),
                ('intervenor_output', models.JSONField(blank=True, null=True)),
                ('llm_call_ids', models.JSONField(blank=True, default=list)),
                ('action', models.CharField(blank=True, choices=[('', ''), ('posted_as_written', 'posted_as_written'), ('edited', 'edited'), ('abandoned', 'abandoned')], default='', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=moderation.models._now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_checks', to='forum.conversation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_checks', to='forum.participant')),
                ('resulting_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preview_checks_resulting', to='forum.message')),
                ('reused_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preview_checks_reused', to='moderation.moderationrun')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', 'created_at'], name='previewcheck_participant_time'), models.Index(fields=['conversation', 'participant', 'draft_sha256'], name='previewcheck_reuse_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ('no_concern', 'concern', 'unavailable'))), name='previewcheck_outcome_valid'), models.CheckConstraint(condition=models.Q(('action__in', ('', 'posted_as_written', 'edited', 'abandoned'))), name='previewcheck_action_valid'), models.CheckConstraint(condition=models.Q(('action', ''), ('resolved_at__isnull', False), _connector='OR'), name='previewcheck_resolved_has_time'), models.CheckConstraint(condition=models.Q(('mode__in', ('on', 'off'))), name='previewcheck_mode_valid')],
            },
        ),
        migrations.CreateModel(
            name='PreviewMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=3)),
                ('assigned_at', models.DateTimeField(default=moderation.models._now)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preview_mode_record', to='forum.conversation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ('on', 'off'))), name='previewmode_mode_valid')],
            },
        ),
    ]
