# Generated by Django 6.1.1 on 2026-09-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_preview_mode_and_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='time_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interventionact',
            name='act_type',
            field=models.CharField(choices=[('provide_information', 'provide_information'), ('correct_factual_error', 'correct_factual_error'), ('improve_argumentation', 'improve_argumentation'), ('clarify_argument', 'clarify_argument'), ('restate_positions', 'restate_positions'), ('identify_agreement_disagreement', 'identify_agreement_disagreement'), ('request_information', 'request_information'), ('request_clarification', 'request_clarification'), ('enforce_conduct', 'enforce_conduct'), ('enforce_process', 'enforce_process'), ('offer_research', 'offer_research')], max_length=40),
        ),
    ]
