# Generated by Django 6.1.1 on 2026-09-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_issue_time_sensitive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='time_sensitive',
            new_name='needs_verification',
        ),
    ]
