# Generated by Django 6.1.1 on 2026-09-27 20:32, hand-edited: see the module docstring below.
"""Adds ModerationRun.source_act / .requested_by and the "research" kind (docs/step20b_brief.md, item 1).

SQLite rebuilds a table when a foreign-key column is added or removed. That drops the triggers migration 0004 put
directly on moderation_moderationrun, and it also breaks the triggers 0004 put on forum_message whose bodies name
moderation_moderationrun in a subquery (moderation_run_trigger_message_stays_user,
moderation_run_posted_message_stays_moderator): mid-rebuild the table briefly doesn't exist under its final name, so
SQLite's rename step fails while re-checking those triggers. Same problem, same fix, as
evaluation/migrations/0002_llm_call_and_annotation_rater_foreign_keys.py: every moderation_run trigger from 0004 is
dropped first and created again at the end, with the exact SQL from 0004, in both directions.
"""
from importlib import import_module

import django.db.models.deletion
from django.db import migrations, models

_0004 = import_module("moderation.migrations.0004_moderation_run_issue_act")
_TRIGGERS = list(_0004._TRIGGERS)  # (name, CREATE statement), all six triggers 0004 put on this table's behalf


def _drop_sql():
    return [f"DROP TRIGGER IF EXISTS {name};" for name, _create in _TRIGGERS]


def _create_sql():
    return [create for _name, create in _TRIGGERS]


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_block'),
        ('moderation', '0007_issue_needs_verification'),
    ]

    operations = [
        migrations.RunSQL(sql=_drop_sql(), reverse_sql=_create_sql()),
        migrations.AddField(
            model_name='moderationrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_requests', to='forum.participant'),
        ),
        migrations.AddField(
            model_name='moderationrun',
            name='source_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_runs', to='moderation.interventionact'),
        ),
        migrations.AlterField(
            model_name='moderationrun',
            name='kind',
            field=models.CharField(choices=[('live', 'live'), ('replay', 'replay'), ('research', 'research')], default='live', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='moderationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'research')), fields=('source_act',), name='moderationrun_one_research_per_act'),
        ),
        migrations.RunSQL(sql=_create_sql(), reverse_sql=_drop_sql()),
    ]
