# Generated by Django 6.1.1 on 2026-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_moderationrun_requested_by_moderationrun_source_act_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='dimension',
            field=models.CharField(blank=True, choices=[('', ''), ('factual_accuracy', 'factual_accuracy'), ('abusiveness', 'abusiveness'), ('clarity', 'clarity')], default='', max_length=30),
        ),
    ]
