"""Regenerates docs/database_schema.md (every table, column, type and constraint) from a freshly migrated scratch SQLite database
plus the Django models. Run: .venv/bin/python scripts/make_schema_doc.py [--html PATH]. Never touches db.sqlite3."""
import html as htmllib
import os
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
tmpdir = tempfile.mkdtemp(prefix="schema_doc_")
os.environ["DJANGO_DB_PATH"] = str(Path(tmpdir) / "schema.sqlite3")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
import django  # noqa: E402

django.setup()
from django.apps import apps  # noqa: E402
from django.core.management import call_command  # noqa: E402
from django.db import connection, models  # noqa: E402

call_command("migrate", verbosity=0)
APPS = ["accounts", "forum", "moderation", "evaluation"]


def triggers_for(table):
    with connection.cursor() as c:
        c.execute("SELECT name, sql FROM sqlite_master WHERE type='trigger' AND tbl_name=%s ORDER BY name", [table])
        rows = c.fetchall()
    out = []
    for name, sql in rows:
        m = re.search(r"BEFORE\s+(INSERT|UPDATE|DELETE)", sql or "", re.I)
        msg = re.search(r"RAISE\s*\(\s*ABORT\s*,\s*'([^']*)'", sql or "", re.I)
        out.append((name, m.group(1).upper() if m else "?", msg.group(1) if msg else ""))
    return out


def cons_text(c):
    if isinstance(c, models.CheckConstraint):
        cond = getattr(c, "condition", None) or getattr(c, "check", None)
        return c.name, "check", str(cond)
    if isinstance(c, models.UniqueConstraint):
        cond = f" only when {c.condition}" if c.condition else ""
        return c.name, "unique", ", ".join(c.fields) + cond
    return c.name, type(c).__name__, ""


data = []
for app in APPS:
    for model in sorted(apps.get_app_config(app).get_models(), key=lambda m: m._meta.model_name):
        meta = model._meta
        with connection.cursor() as c:
            c.execute(f'PRAGMA table_info("{meta.db_table}")')
            cols = {r[1]: r for r in c.fetchall()}
        fields = []
        for f in meta.concrete_fields:
            col = cols.get(f.column)
            notes = []
            if f.primary_key:
                notes.append("primary key")
            if isinstance(f, models.ForeignKey):
                od = getattr(f.remote_field.on_delete, "__name__", str(f.remote_field.on_delete))
                notes.append(f"foreign key to {f.related_model._meta.label} (on delete {od})")
            if f.unique and not f.primary_key:
                notes.append("unique")
            if f.choices:
                notes.append("one of: " + ", ".join(str(ch[0]) for ch in f.choices))
            if f.has_default() and f.default is not models.NOT_PROVIDED:
                d = f.default
                notes.append("default " + (d.__name__ + "()" if callable(d) else repr(d)))
            if getattr(f, "max_length", None):
                notes.append(f"max {f.max_length} characters")
            if isinstance(f, models.DecimalField):
                notes.append(f"{f.max_digits} digits, {f.decimal_places} decimals")
            if f.db_index and not f.unique and not f.primary_key:
                notes.append("indexed")
            fields.append((f.column, col[2] if col else "?", "no" if (col and col[3]) else "yes", "; ".join(notes)))
        cons = [cons_text(c) for c in meta.constraints] + [("unique together", "unique", ", ".join(u)) for u in meta.unique_together]
        idx = [(i.name, ", ".join(i.fields)) for i in meta.indexes]
        data.append((app, meta.object_name, meta.db_table, fields, cons, idx, triggers_for(meta.db_table)))

md = ["# Database schema", "", "Generated by `scripts/make_schema_doc.py` from a freshly migrated scratch database (never `db.sqlite3`). Do not edit by hand.",
      "Column types are SQLite's. `null` says whether the column accepts NULL. Django adds no database default: defaults listed apply in the application.", ""]
for app, name, table, fields, cons, idx, trg in data:
    md += [f"## {name}  (`{table}`, app {app})", "", "| column | SQLite type | null | notes |", "|---|---|---|---|"]
    md += [f"| {c} | {t} | {n} | {notes} |" for c, t, n, notes in fields]
    if cons:
        md += ["", "Constraints:"] + [f"- `{n}` ({k}): {d}" for n, k, d in cons]
    if idx:
        md += ["", "Extra indexes:"] + [f"- `{n}`: {d}" for n, d in idx]
    if trg:
        md += ["", "Database triggers (rules the database itself enforces):"] + [f"- `{n}` on {ev}: {msg}" for n, ev, msg in trg]
    md.append("")
(ROOT / "docs" / "database_schema.md").write_text("\n".join(md) + "\n")

if "--html" in sys.argv:
    out = Path(sys.argv[sys.argv.index("--html") + 1])
    e = htmllib.escape
    parts = []
    for app, name, table, fields, cons, idx, trg in data:
        rows = "".join(f"<tr><td><code>{e(c)}</code></td><td>{e(t)}</td><td>{e(n)}</td><td>{e(notes)}</td></tr>" for c, t, n, notes in fields)
        extra = ""
        if cons:
            extra += "<h4>Constraints</h4><ul>" + "".join(f"<li><code>{e(n)}</code> ({e(k)}): {e(d)}</li>" for n, k, d in cons) + "</ul>"
        if trg:
            extra += "<h4>Database triggers</h4><ul>" + "".join(f"<li><code>{e(n)}</code> on {e(ev)}: {e(msg)}</li>" for n, ev, msg in trg) + "</ul>"
        parts.append(f'<details id="{e(name)}"><summary><b>{e(name)}</b> <span class="app">{e(app)} · {e(table)}</span></summary>'
                     f'<div class="tbl"><table><thead><tr><th>column</th><th>type</th><th>null</th><th>notes</th></tr></thead><tbody>{rows}</tbody></table></div>{extra}</details>')
    out.write_text("\n".join(parts))
print(len(data), "tables")
